-- Create the table anew
create table bookmark (
  id INTEGER primary key generated by default as identity,
  title TEXT,
  description TEXT,
  rating INTEGER
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmark (title, description, rating)
values
  ('Left', 'Left hand goes left', 3),
  ('Right', 'Right hand goes right', 4),
  ('Center', 'Center hand goes forward', 5);